const sampleData = {
  vegetarian: false,
  vegan: false,
  glutenFree: true,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 3,
  gaps: "no",
  preparationMinutes: null,
  cookingMinutes: null,
  aggregateLikes: 4,
  healthScore: 16,
  creditsText: "foodista.com",
  sourceName: "foodista.com",
  pricePerServing: 116.83,
  extendedIngredients: [
    {
      id: 10225,
      aisle: "Meat",
      image: "pork-loin.jpg",
      consistency: "SOLID",
      name: "pork loin",
      nameClean: "boneless pork roast",
      original: "2 pounds boneless pork loin",
      originalName: "boneless pork loin",
      amount: 2,
      unit: "pounds",
      meta: ["boneless"],
      measures: {
        us: {
          amount: 2,
          unitShort: "lb",
          unitLong: "pounds",
        },
        metric: {
          amount: 907.185,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 19334,
      aisle: "Baking",
      image: "light-brown-sugar.jpg",
      consistency: "SOLID",
      name: "brown sugar",
      nameClean: "golden brown sugar",
      original: "1/4 cup brown sugar",
      originalName: "brown sugar",
      amount: 0.25,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 55,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 19334,
      aisle: "Baking",
      image: "dark-brown-sugar.png",
      consistency: "SOLID",
      name: "brown sugar",
      nameClean: "golden brown sugar",
      original: "1/4 cup brown sugar",
      originalName: "brown sugar",
      amount: 0.25,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 55,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 93749,
      aisle: "Ethnic Foods",
      image: "chili-garlic-sauce.jpg",
      consistency: "LIQUID",
      name: "chili garlic sauce",
      nameClean: "chili garlic sauce",
      original: "3 teaspoons chili garlic sauce",
      originalName: "chili garlic sauce",
      amount: 3,
      unit: "teaspoons",
      meta: [],
      measures: {
        us: {
          amount: 3,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 3,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 10211216,
      aisle: "Produce",
      image: "ginger.png",
      consistency: "SOLID",
      name: "ginger",
      nameClean: "fresh ginger",
      original: "2 teaspoons fresh ginger, minced",
      originalName: "fresh ginger, minced",
      amount: 2,
      unit: "teaspoons",
      meta: ["fresh", "minced"],
      measures: {
        us: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 10211215,
      aisle: "Produce",
      image: "garlic.jpg",
      consistency: "SOLID",
      name: "garlic cloves",
      nameClean: "whole garlic cloves",
      original: "6 garlic cloves, minced",
      originalName: "garlic cloves, minced",
      amount: 6,
      unit: "",
      meta: ["minced"],
      measures: {
        us: {
          amount: 6,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 6,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 1022053,
      aisle: "Ethnic Foods",
      image: "rice-vinegar.png",
      consistency: "LIQUID",
      name: "rice vinegar",
      nameClean: "rice vinegar",
      original: "rice vinegar",
      originalName: "rice vinegar",
      amount: 10,
      unit: "servings",
      meta: [],
      measures: {
        us: {
          amount: 10,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 10,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 4058,
      aisle: "Ethnic Foods",
      image: "sesame-oil.png",
      consistency: "LIQUID",
      name: "sesame oil",
      nameClean: "sesame oil",
      original: "2 teaspoons sesame oil",
      originalName: "sesame oil",
      amount: 2,
      unit: "teaspoons",
      meta: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 2,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 16124,
      aisle: "Condiments",
      image: "soy-sauce.jpg",
      consistency: "LIQUID",
      name: "soy sauce",
      nameClean: "soy sauce",
      original: "1/4 cup soy sauce",
      originalName: "soy sauce",
      amount: 0.25,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 58,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
  ],
  id: 661117,
  title: "Spicy Korean Bbq Pork",
  readyInMinutes: 45,
  servings: 10,
  sourceUrl: "https://www.foodista.com/recipe/6C67RJHP/spicy-korean-bbq-pork",
  image: "https://img.spoonacular.com/recipes/661117-556x370.jpg",
  imageType: "jpg",
  summary:
    'The recipe Spicy Korean Bbq Pork is ready <b>in roughly 45 minutes</b> and is definitely a spectacular <b>gluten free and dairy free</b> option for lovers of Korean food. For <b>$1.17 per serving</b>, you get a main course that serves 10. One serving contains <b>157 calories</b>, <b>21g of protein</b>, and <b>5g of fat</b>. This recipe from Foodista requires rice vinegar, garlic cloves, chili garlic sauce, and soy sauce. This recipe is liked by 4 foodies and cooks. All things considered, we decided this recipe <b>deserves a spoonacular score of 63%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/spicy-korean-bbq-pork-1527885">Spicy Korean Bbq Pork</a>, <a href="https://spoonacular.com/recipes/daeji-bulgogi-korean-spicy-bbq-pork-249076">Daeji Bulgogi (Korean Spicy BBQ Pork)</a>, and <a href="https://spoonacular.com/recipes/grilled-korean-bbq-short-rib-dogs-with-sweet-peach-relish-spicy-korean-slaw-549399">Grilled Korean BBQ Short Rib Dogs with Sweet Peach Relish + Spicy Korean Slaw</a> for similar recipes.',
  cuisines: ["Korean", "Asian"],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["gluten free", "dairy free"],
  occasions: [],
  instructions:
    "<ol><li>Mix the marinade ingredients (brown sugar, soy sauce, ginger, sesame oil, chili garlic sauce, and ginger). Pour over your sliced pork.</li><li>Marinate no less then 4 hours; overnight is recommended.</li><li>Preheat your grill to high. Place pork on grill and grill each side 3 minutes or until cooked through.</li><li>If you want a sauce to pour over your meat, boil your leftover marinade in a sauce pan for a few minutes until it boils down and thickens. You can then add rice vinegar to taste to thin it and decrease the sweetness. Pour sauce over meat.</li></ol>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Mix the marinade ingredients (brown sugar, soy sauce, ginger, sesame oil, chili garlic sauce, and ginger).",
          ingredients: [
            {
              id: 93749,
              name: "chili garlic sauce",
              localizedName: "chili garlic sauce",
              image: "chili-garlic-sauce.jpg",
            },
            {
              id: 19334,
              name: "brown sugar",
              localizedName: "brown sugar",
              image: "dark-brown-sugar.png",
            },
            {
              id: 4058,
              name: "sesame oil",
              localizedName: "sesame oil",
              image: "sesame-oil.png",
            },
            {
              id: 16124,
              name: "soy sauce",
              localizedName: "soy sauce",
              image: "soy-sauce.jpg",
            },
            {
              id: 0,
              name: "marinade",
              localizedName: "marinade",
              image: "seasoning.png",
            },
            {
              id: 11216,
              name: "ginger",
              localizedName: "ginger",
              image: "ginger.png",
            },
          ],
          equipment: [],
        },
        {
          number: 2,
          step: "Pour over your sliced pork.Marinate no less then 4 hours; overnight is recommended.Preheat your grill to high.",
          ingredients: [
            {
              id: 10010219,
              name: "pork",
              localizedName: "pork",
              image: "pork-tenderloin-raw.png",
            },
          ],
          equipment: [
            {
              id: 404706,
              name: "grill",
              localizedName: "grill",
              image: "https://spoonacular.com/cdn/equipment_100x100/grill.jpg",
            },
          ],
          length: {
            number: 240,
            unit: "minutes",
          },
        },
        {
          number: 3,
          step: "Place pork on grill and grill each side 3 minutes or until cooked through.If you want a sauce to pour over your meat, boil your leftover marinade in a sauce pan for a few minutes until it boils down and thickens. You can then add rice vinegar to taste to thin it and decrease the sweetness.",
          ingredients: [
            {
              id: 1022053,
              name: "rice vinegar",
              localizedName: "rice vinegar",
              image: "rice-vinegar.png",
            },
            {
              id: 0,
              name: "marinade",
              localizedName: "marinade",
              image: "seasoning.png",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 1065062,
              name: "meat",
              localizedName: "meat",
              image: "whole-chicken.jpg",
            },
            {
              id: 10010219,
              name: "pork",
              localizedName: "pork",
              image: "pork-tenderloin-raw.png",
            },
          ],
          equipment: [
            {
              id: 404669,
              name: "sauce pan",
              localizedName: "sauce pan",
              image:
                "https://spoonacular.com/cdn/equipment_100x100/sauce-pan.jpg",
            },
            {
              id: 404706,
              name: "grill",
              localizedName: "grill",
              image: "https://spoonacular.com/cdn/equipment_100x100/grill.jpg",
            },
          ],
          length: {
            number: 3,
            unit: "minutes",
          },
        },
        {
          number: 4,
          step: "Pour sauce over meat.",
          ingredients: [
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 1065062,
              name: "meat",
              localizedName: "meat",
              image: "whole-chicken.jpg",
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 66.97755432128906,
  spoonacularSourceUrl: "https://spoonacular.com/spicy-korean-bbq-pork-661117",
};

export type RecipeType = typeof sampleData;
